noun_1 = input("Please enter a noun")
adjective_ic_1 = input("Please enter an adjective ending with -ic")
noun_2 = input("Please enter another noun")
noun_3 = input("Please enter another noun")
verb_ing = input("Please enter a verb that ends in -ing")
noun_4 = input("Please enter another noun")
onomatopoeia = input("Please enter an onomatopoeia")
noun_5 = input("Please enter another noun")
onomatopoeia_2 = input("Please enter another onomatopoeia")
noun_6 = input("Please input the final noun")

print("The %s™ Pacer Test is a multi-stage %s capacity "
      "test that progressively gets more difficult as it continues." % (noun_1 , adjective_ic_1))
print()
print("The 20-%s Pacer test will begin in 30 %s. Line up at the start. " % (noun_2, noun_3))
print("The %s speed starts slowly, but gets faster every %s after you hear this signal: *%s*" % (verb_ing, noun_4,
                                                                                                 onomatopoeia))
print()
print("A single %s should be completed every time you hear this sound: *%s*" % (noun_5, onomatopoeia_2))
print()
print("The second time you fail to complete a lap, your test is over. ")
print()
print("The test will begin on the word %s. Ready? Set? %a." % noun_6)
