noun_1 = input("Plural Noun")
noun_2 = input("noun")
verb_ing_1 = input("Verb ending in -ing")


print("Building %s is a creative process." % noun_1)
print()
print("It is not just a matter of laying out the %s and %s the %s." % (noun_2, verb_ing_1, noun_1))
print("Truly engaging apps must take advantage of the capabilities of a mobile device.")
print()
print("If you were part of a team that was building a new app, what would you consider in the design?")
print()
print("Remember that tablets and smart phones are miniature computers")
print("that can do so much more than laptops and desktops.")
print()
print("Mobile devices have sensing and audio-visual capabilities,")
print("are location aware, and can give and receive information")
print()
print("from the user’s hands through the touch screen and the small motor inside that vibrates the phone.")
